apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice-master-configmap
  namespace: api-namespace
data:
  KEYCLOAK_ADMIN_USERNAME: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  EUREKA_HOST: "http://discovery-service:8081/discovery/eureka/"
